package com.mate.velkey.links.model.link;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.mate.velkey.links.model.image.Image;

import java.util.List;

@DynamoDBTable(tableName = "link-image-table")
public class Link {

    @DynamoDBHashKey(attributeName = "LinkId")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "LinkName")
    private String name;
    @DynamoDBAttribute(attributeName = "LinkUrl")
    private String url;
    @DynamoDBAttribute(attributeName = "LinkLabel")
    private List<String> label;
    @DynamoDBAttribute(attributeName = "LinkImage")
    private Image image;

    public Link() {
    }

    private Link(Builder builder) {
        this.name = builder.name;
        this.url = builder.url;
        this.label = builder.label;
        this.image = builder.image;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public List<String> getLabel() {
        return label;
    }

    public void setLabel(List<String> label) {
        this.label = label;
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {

        private String name;
        private String url;
        private List<String> label;
        private Image image;

        public Builder withName(String name) {
            this.name = name;
            return this;
        }

        public Builder withUrl(String url) {
            this.url = url;
            return this;
        }

        public Builder withLabel(List<String> label) {
            this.label = label;
            return this;
        }

        public Builder withImage(Image image) {
            this.image = image;
            return this;
        }

        public Link build() {
            return new Link(this);
        }
    }
}
